hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "6e6eaefbfaef2bcc5f1fae83112b3a6ab311c84ef776f389d13d49a500a52217"
metafile = true

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "4630f59c3ac70d37641704833a8cc94171eb02697969277159b749ea15e74c00"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "b99f8b297b9429f5185c84805d1a67f650bba836cf83c6c9d81b275261169672"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a8fb4be44cbfe7835c4ebfeae4fa89f7dd71965fef08e5671f77b625b4e06414"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "90de023b54d15536a49e98bd4b79319940381bad60e8ca9798a4f5468b9b156f"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "cb813029826c5dcbbd9deee45f82e913f51a7e37b488bb330781908d25957ad6"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "67239981d8f29860e0de6d2462630a9eeb839ee44b633c3dc3d41e8760426a08"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "af1eb4731779edc72e1e1cb1664dd74328e0edb1da05805a0a694b10c48d010b"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "76e805480f5d9c407dbc502f41517af86156d0c6504a1d7f2b8fc6294ae6de81"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "753859b58aa7a674785b3ec5a8080c2142209a50185cc3dd5ab90c7c6a38f5ee"
metafile = true

[[files]]
file = "mods/charmonium.pw.toml"
hash = "d16e0db41806840dc72dfa44174896e088dd325249fc17ca0dac69af9fdc0518"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "d2bb03cee21d84e8e72fccc06cc8afbd6760674a7b8629a3fcba98e24503008e"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "955b5160e856fbc93b615ad021e78421383177db29a1b0bc451e2840ad659f79"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "749bf88d67ff9ddf272dc48d82402dd61ea2812238dfca4feb1fd78440675456"
metafile = true

[[files]]
file = "mods/couplings.pw.toml"
hash = "a849de7db80785ba8205d5eb91d310c6211b27e1d6447386bb955cceae098e92"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "cb14cb30c723d1ed83f1d612b61b12134ea3a39fcff3ae02c2aedc2c1aa12a67"
metafile = true

[[files]]
file = "mods/dcwa.pw.toml"
hash = "6ec1e483b01e1feb7bb64f2f017bfd0f8a28b48a863b0c325ab7c78c86b9e2ad"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "6cb34219f7edaae938e9f4edabe1ee15742c6784d59dc97fc3e6df4a5e24d850"
metafile = true

[[files]]
file = "mods/entity-collision-fps-fix.pw.toml"
hash = "d614e471929c4906f85ba776600e0cfa9b0d958ce55121efd49c9ffd4ff00a04"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5f7e8ec1787dc7e2c8556596c2ba53c0dae9828bf1a2d9c6a1f8b8f9ba41dfb7"
metafile = true

[[files]]
file = "mods/erroring-entity-remover.pw.toml"
hash = "288d7f7991a50a12c63625b7f10fb171c05c0509684d5e1b83d14ee504277ff6"
metafile = true

[[files]]
file = "mods/extrasounds.pw.toml"
hash = "f01d3f9aa3d496e168c742b298efa9744eb868eb8a6c3c7ec91c06e704020af5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "9ae76046167e451e37eb846a72b8ff2b04b997767b717b37f4c8c586f08a5ef6"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "0b0b7d2de5e46b9032ae84b25f554839e7fabfeab7bd8bcb48392b940e112f38"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "200797c3f731a126fad409a7afa6e737af4a1e860a0d6954b48b18bb0922f3ec"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "3e84222a0d8020efe132dff80b2fc01ff9a1768dcc39f5e41a80bf7cf501a628"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d87f8c04eeed21a9544cfad7f64afee6de58b5249a70b0367ba8522273a4816"
metafile = true

[[files]]
file = "mods/horsebuff.pw.toml"
hash = "5fbf5aede28e57f2f462d6bffaf12b30d0b1cf5692e7e19d5fddf0fb76d2218a"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "86fd4c1bb6f13fa109dfd1aa1e9cb84ffe71408de8da790b21d9756972740ad1"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "26894893b73719ef3dd79e4a8b11bf407f5bd7987679b41c1f01fd454e82dfc1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "e516d6d036f6d407a793c3b9a1fc5a8a817b05c9dc9d8677003fb0a512b2bf6f"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "a2bb983e5dffe95d1f92ee19a099ed214f9b3d39c4e9f8eb5991a1a3c7735b45"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8fb914c75a06a677721dd1fc880606d790886be9e0b392820dcecb9bb56e0786"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "f264c166b22cf93af5e44a3d65931e2a46008d11ee0cd81f209a3af54979a760"
metafile = true

[[files]]
file = "mods/mambience.pw.toml"
hash = "655919b6f75cc94b66beb2054d8b1b1fc9a214566c85f6f2b694ddd79abfdba9"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "dc1f47a526f2264dc215437a81668d54c084d5beaaa6cbf6e284b88a59af88b5"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "f0a7c49ae4417a753722da78046a7513e059e5964e21154f4aef50df6a1d6ed0"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "130550012d1bb91595fd441bc1214d28ddb1916d045dfca3875ca422fbd27b92"
metafile = true

[[files]]
file = "mods/no-telemetry.pw.toml"
hash = "bcbc4091875a9f83813374950be1b9a1f89ac26f393afa54c85c29614069acf4"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "91e24178f86243b32a8516ceefd1f21b054d7c963e44f274ddfede8d8d41c027"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3617f55f5973b7dcaab7ae5098db9f3daf6d5e89123c0a58301333435dda6e03"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "ce188971c0534b989e14ab1a0a6efb01a3fe871373a8f9522a4e40d31a19d672"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b4d8e22f7916c1a2e8be07b708cd02d16bd730e382bb7ca36a615cf3e6782940"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "8cee882d886709a92b1c2ba19e6c5d1a55da9cc6ed79b78d62eec98b5b768588"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "22e15c00bdfedc47f9cd8c49df95ae8cc8fd1e061eec0cc92925da565e0866a8"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "ce35c771c56cb887819ac75b6f6df59d13a3477422cf7009d22cc637f8dba91f"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "60b86b7eb16a4e3e12dd866cc63194263ba7e7c8abd8dff7ae52a1ea52017f33"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8bdc3c1b5079b7fbe89f995d1a100e1df8dcf47e73ef089abf444ecc8e320527"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0d539d8bad8493d4196bf5f7bf216d692384f283849fa41a2e5a816a0147673e"
metafile = true

[[files]]
file = "mods/sound-categories.pw.toml"
hash = "41e20f830b542cc205e9f6cd7643506eeb17fba6d8e1b47cc7d60852b6ecfe1d"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "b48a96a91849dec6ef853b6e3b7112be1860df95b3dc803842bef0bf2d725993"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "0212996355de904aa968661624fd9230d1b31d85b201b9ab01bb9e94ac0fe73c"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "eda1cc1a41819d633cc5161ea985aa3f4cbf8f7901496bbde160c885ea808628"
metafile = true
